### PR TITLE
Add call status view for the help request

### PR DESCRIPTION
**Pull request by kosiakkatrina**
Add call status in help request edit view with number of calls, voicemails, date requested and status of the last call.
image

### CODE REVIEW

**Review by maysakanoni — APPROVED** [review]

**Comment by antonyoneill** [comment]
Got a couple of tests failing @kosiakkatrina - may be caused by the structural changes

**Comment by antonyoneill** [comment]
Turns out I have the same tests failing on my branch :(

**Comment by antonyoneill** [comment]
Think I found the fix, it's because we've added another help request type and the tests are tightly coupled to the order of those request types.

**Comment by kosiakkatrina** [comment]
I guess that makes sense.. It's throwing errors on the screen in my tests tho, so I'll investigate a bit more 😅

**Pull request merged**
